version: '3.7'

services:
  backend:
    build: .
    stdin_open: true
    tty: true
    command: bash -c "rm -f tmp/pids/server.pid && rails s -b '0.0.0.0'"
    environment:
      - DATABASE_URL=mysql2://root:@mysql:3306
      - DEFAULT_HOST=localhost:8030
    volumes:
      - .:/app:cached
      - bundle:/bundle
      - node_modules:/app/node_modules
    depends_on:
      - mysql
    ports:
      - '8030:3000'
  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  bundle:
  node_modules: